#############################################################################
# Makefile for building: bin/cap3dfumo
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Apr 24 15:54:59 2018
# Project:  visualizador.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile visualizador.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -Itemp -Itemp
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -lGLU -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Scene.cpp \
		src/math/Vec3.cpp \
		src/qtgui/glwidget.cpp \
		src/qtgui/main.cpp \
		src/qtgui/mainwindow.cpp \
		src/qtgui/trackball.cpp \
		src/importer.cpp \
		src/math/point3d.cpp \
		src/Object.cpp \
		src/BoundingBox.cpp temp/moc_glwidget.cpp \
		temp/moc_mainwindow.cpp \
		temp/qrc_image.cpp
OBJECTS       = obj/Scene.o \
		obj/Vec3.o \
		obj/glwidget.o \
		obj/main.o \
		obj/mainwindow.o \
		obj/trackball.o \
		obj/importer.o \
		obj/point3d.o \
		obj/Object.o \
		obj/BoundingBox.o \
		obj/moc_glwidget.o \
		obj/moc_mainwindow.o \
		obj/qrc_image.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		visualizador.pro
QMAKE_TARGET  = cap3dfumo
DESTDIR       = bin/
TARGET        = bin/cap3dfumo

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): temp/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: visualizador.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile visualizador.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile visualizador.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/cap3dfumo1.0.0 || $(MKDIR) obj/cap3dfumo1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/cap3dfumo1.0.0/ && $(COPY_FILE) --parents src/Scene.h src/math/Vec3.h src/qtgui/glwidget.h src/qtgui/mainwindow.h src/qtgui/trackball.h src/utility.h src/importer.h src/math/Point.h src/math/point3d.h src/Object.h src/BoundingBox.h obj/cap3dfumo1.0.0/ && $(COPY_FILE) --parents image.qrc obj/cap3dfumo1.0.0/ && $(COPY_FILE) --parents src/Scene.cpp src/math/Vec3.cpp src/qtgui/glwidget.cpp src/qtgui/main.cpp src/qtgui/mainwindow.cpp src/qtgui/trackball.cpp src/importer.cpp src/math/point3d.cpp src/Object.cpp src/BoundingBox.cpp obj/cap3dfumo1.0.0/ && $(COPY_FILE) --parents src/qtgui/mainwindow.ui obj/cap3dfumo1.0.0/ && (cd `dirname obj/cap3dfumo1.0.0` && $(TAR) cap3dfumo1.0.0.tar cap3dfumo1.0.0 && $(COMPRESS) cap3dfumo1.0.0.tar) && $(MOVE) `dirname obj/cap3dfumo1.0.0`/cap3dfumo1.0.0.tar.gz . && $(DEL_FILE) -r obj/cap3dfumo1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: temp/moc_glwidget.cpp temp/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/moc_glwidget.cpp temp/moc_mainwindow.cpp
temp/moc_glwidget.cpp: src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h \
		src/qtgui/glwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/qtgui/glwidget.h -o temp/moc_glwidget.cpp

temp/moc_mainwindow.cpp: src/qtgui/glwidget.h \
		src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h \
		src/qtgui/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/qtgui/mainwindow.h -o temp/moc_mainwindow.cpp

compiler_rcc_make_all: temp/qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) temp/qrc_image.cpp
temp/qrc_image.cpp: image.qrc \
		data/Programs.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name image image.qrc -o temp/qrc_image.cpp

compiler_image_collection_make_all: temp/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) temp/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: temp/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) temp/ui_mainwindow.h
temp/ui_mainwindow.h: src/qtgui/mainwindow.ui \
		src/qtgui/glwidget.h \
		src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/qtgui/mainwindow.ui -o temp/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/Scene.o: src/Scene.cpp src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Scene.o src/Scene.cpp

obj/Vec3.o: src/math/Vec3.cpp src/math/Vec3.h \
		src/utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Vec3.o src/math/Vec3.cpp

obj/glwidget.o: src/qtgui/glwidget.cpp src/qtgui/glwidget.h \
		src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h \
		src/qtgui/trackball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/glwidget.o src/qtgui/glwidget.cpp

obj/main.o: src/qtgui/main.cpp src/qtgui/mainwindow.h \
		src/qtgui/glwidget.h \
		src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/qtgui/main.cpp

obj/mainwindow.o: src/qtgui/mainwindow.cpp src/qtgui/mainwindow.h \
		src/qtgui/glwidget.h \
		src/Scene.h \
		src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h \
		temp/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/mainwindow.o src/qtgui/mainwindow.cpp

obj/trackball.o: src/qtgui/trackball.cpp src/qtgui/trackball.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/trackball.o src/qtgui/trackball.cpp

obj/importer.o: src/importer.cpp src/importer.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/importer.o src/importer.cpp

obj/point3d.o: src/math/point3d.cpp src/math/point3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/point3d.o src/math/point3d.cpp

obj/Object.o: src/Object.cpp src/Object.h \
		src/math/Point.h \
		src/math/Vec3.h \
		src/utility.h \
		src/importer.h \
		src/BoundingBox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/Object.o src/Object.cpp

obj/BoundingBox.o: src/BoundingBox.cpp src/BoundingBox.h \
		src/math/Vec3.h \
		src/utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/BoundingBox.o src/BoundingBox.cpp

obj/moc_glwidget.o: temp/moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_glwidget.o temp/moc_glwidget.cpp

obj/moc_mainwindow.o: temp/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_mainwindow.o temp/moc_mainwindow.cpp

obj/qrc_image.o: temp/qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_image.o temp/qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

